[package]
name = "sencha-cli"
description = "Sencha command-line interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "sencha"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
